% Generated by purerl version 0.0.24
-module(testClosure@ps).
-export([test/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./testClosure.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/TestClosure.purs", 3).
-spec test() -> integer().
test() -> 
  F@4 = fun F(X) ->
    fun (Y) ->
      X + Y
    end
  end,
  ((F@4(1))(2))
.
