% Generated by purerl version 0.0.24
-module(test_listOps@ps).
-export(['Nil'/0, 'Cons'/0, range/2, range/0, foldl/3, foldl/0, filterEvens/1, filterEvens/0, sumEvens/0, describe/0, act/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./test_listOps.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 7).
-spec 'Nil'() -> any().
'Nil'() -> { nil }.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 7).
-spec 'Cons'() -> any().
'Cons'() -> fun (Value0) ->
  fun (Value1) ->
    { cons, Value0, Value1 }
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 9).
-spec range(integer(),integer()) -> test_listOps_List(integer()).
range(_@17,_@18) -> 
  Go@f@50@52 = fun
    Reccase({ Go@f }) -> 
    fun (Curr) ->
      fun (Acc) ->
        case Curr < _@17 of
          (true) -> Acc;
          (_) -> (((Go@f({ Go@f }))(Curr - 1))({ cons, Curr, Acc }))
        end
      end
    end
  end,
  Go@51@53 = (Go@f@50@52({ Go@f@50@52 })),
  ((Go@51@53(_@18))({ nil }))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 9).
-spec range() -> fun((integer()) -> fun((integer()) -> test_listOps_List(integer()))).
range() -> fun (_@20) ->
  fun (_@21) ->
    (range(_@20, _@21))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 24).
-spec foldl(fun((any()) -> fun((any()) -> any())),any(),test_listOps_List(any())) -> any().
foldl(_@27,_@28,_@29) -> case { _@27, _@28, _@29 } of
  ({ _, _@30, { nil } }) -> _@30;
  ({ _@31, _@32, { cons, _@33, _@34 } }) -> (foldl(_@31, ((_@31(_@32))(_@33)), _@34))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 24).
-spec foldl() -> fun((fun((any()) -> fun((any()) -> any()))) -> fun((any()) -> fun((test_listOps_List(any())) -> any()))).
foldl() -> fun (_@35) ->
  fun (_@36) ->
    fun (_@37) ->
      (foldl(_@35, _@36, _@37))
    end
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 16).
-spec filterEvens(test_listOps_List(integer())) -> test_listOps_List(integer()).
filterEvens(_@43) -> 
  Go@f@54 = fun
    Reccase({ Go@f }) -> 
    fun (V) ->
      fun (V1) ->
        case { V, V1 } of
          ({ { nil }, _@45 }) -> _@45;
          ({ { cons, _@46, _@47 }, _@48 }) -> case (((?MEMOIZE((data_euclideanRing@ps:mod((data_euclideanRing@ps:euclideanRingInt())))))(_@46))(2)) =:= 0 of
            (true) -> (((Go@f({ Go@f }))(_@47))({ cons, _@46, _@48 }));
            (_) -> (((Go@f({ Go@f }))(_@47))(_@48))
          end
        end
      end
    end
  end,
  Go@55 = (Go@f@54({ Go@f@54 })),
  ((Go@55(_@43))({ nil }))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 16).
-spec filterEvens() -> fun((test_listOps_List(integer())) -> test_listOps_List(integer())).
filterEvens() -> fun (_@49) ->
  (filterEvens(_@49))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 28).
-spec sumEvens() -> integer().
sumEvens() -> (foldl((?MEMOIZE((data_semiring@ps:add((data_semiring@ps:semiringInt()))))), 0, (filterEvens((range(1, 900)))))).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 31).
-spec describe() -> fun(() -> any()).
describe() -> (effect_console@ps:log(<<"List Processing (900 elements):"/utf8>>)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/ListOps.purs", 34).
-spec act() -> fun(() -> any()).
act() -> (effect_console@ps:logShow((data_show@ps:showInt()), (sumEvens()))).
