% Generated by purerl version 0.0.24
-module(test_primes@ps).
-export(['Nil'/0, 'Cons'/0, sumList/1, sumList/0, reverse/1, reverse/0, range/2, range/0, filter/2, filter/0, sieve/1, sieve/0, describe/0, act/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./test_primes.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 13).
-spec 'Nil'() -> any().
'Nil'() -> { nil }.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 13).
-spec 'Cons'() -> any().
'Cons'() -> fun (Value0) ->
  fun (Value1) ->
    { cons, Value0, Value1 }
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 43).
-spec sumList(test_primes_List(integer())) -> integer().
sumList(_@25) -> 
  Go@f@70 = fun
    Reccase({ Go@f }) -> 
    fun (V) ->
      fun (V1) ->
        case { V, V1 } of
          ({ { nil }, _@27 }) -> _@27;
          ({ { cons, _@28, _@29 }, _@30 }) -> (((Go@f({ Go@f }))(_@29))(_@30 + _@28))
        end
      end
    end
  end,
  Go@71 = (Go@f@70({ Go@f@70 })),
  ((Go@71(_@25))(0))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 43).
-spec sumList() -> fun((test_primes_List(integer())) -> integer()).
sumList() -> fun (_@31) ->
  (sumList(_@31))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 32).
-spec reverse(test_primes_List(any())) -> test_primes_List(any()).
reverse(_@37) -> 
  Go@f@72 = fun
    Reccase({ Go@f }) -> 
    fun (V) ->
      fun (V1) ->
        case { V, V1 } of
          ({ { nil }, _@39 }) -> _@39;
          ({ { cons, _@40, _@41 }, _@42 }) -> (((Go@f({ Go@f }))(_@41))({ cons, _@40, _@42 }))
        end
      end
    end
  end,
  Go@73 = (Go@f@72({ Go@f@72 })),
  ((Go@73(_@37))({ nil }))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 32).
-spec reverse() -> fun((test_primes_List(any())) -> test_primes_List(any())).
reverse() -> fun (_@43) ->
  (reverse(_@43))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 15).
-spec range(integer(),integer()) -> test_primes_List(integer()).
range(_@45,_@46) -> 
  Go@f@74@76 = fun
    Reccase({ Go@f }) -> 
    fun (Curr) ->
      fun (Acc) ->
        case Curr < _@45 of
          (true) -> Acc;
          (_) -> (((Go@f({ Go@f }))(Curr - 1))({ cons, Curr, Acc }))
        end
      end
    end
  end,
  Go@75@77 = (Go@f@74@76({ Go@f@74@76 })),
  ((Go@75@77(_@46))({ nil }))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 15).
-spec range() -> fun((integer()) -> fun((integer()) -> test_primes_List(integer()))).
range() -> fun (_@48) ->
  fun (_@49) ->
    (range(_@48, _@49))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 23).
-spec filter(fun((any()) -> boolean()),test_primes_List(any())) -> test_primes_List(any()).
filter(_@55,_@56) -> 
  Go@f@78@80 = fun
    Reccase({ Go@f }) -> 
    fun (V) ->
      fun (V1) ->
        case { V, V1 } of
          ({ { nil }, _@58 }) -> (reverse(_@58));
          ({ { cons, _@59, _@60 }, _@61 }) -> case (_@55(_@59)) of
            (true) -> (((Go@f({ Go@f }))(_@60))({ cons, _@59, _@61 }));
            (_) -> (((Go@f({ Go@f }))(_@60))(_@61))
          end
        end
      end
    end
  end,
  Go@79@81 = (Go@f@78@80({ Go@f@78@80 })),
  ((Go@79@81(_@56))({ nil }))
.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 23).
-spec filter() -> fun((fun((any()) -> boolean())) -> fun((test_primes_List(any())) -> test_primes_List(any()))).
filter() -> fun (_@62) ->
  fun (_@63) ->
    (filter(_@62, _@63))
  end
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 39).
-spec sieve(test_primes_List(integer())) -> test_primes_List(integer()).
sieve(_@66) -> case _@66 of
  ({ nil }) -> { nil };
  ({ cons, _@67, _@68 }) -> { cons, _@67, (sieve((filter(fun (X) ->
    (((?MEMOIZE((data_euclideanRing@ps:mod((data_euclideanRing@ps:euclideanRingInt())))))(X))(_@67)) =/= 0
  end, _@68)))) }
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 39).
-spec sieve() -> fun((test_primes_List(integer())) -> test_primes_List(integer())).
sieve() -> fun (_@69) ->
  (sieve(_@69))
end.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 52).
-spec describe() -> fun(() -> any()).
describe() -> (effect_console@ps:log(<<"Prime Sieve (sum primes up to 500):"/utf8>>)).
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/Test/Primes.purs", 55).
-spec act() -> fun(() -> any()).
act() -> (effect_console@ps:logShow((data_show@ps:showInt()), (sumList((sieve((range(2, 500)))))))).
